//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit_console.Logging {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class LogTypes : global::System.Configuration.ApplicationSettingsBase {
        
        private static LogTypes defaultInstance = ((LogTypes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LogTypes())));
        
        public static LogTypes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[General] Unhandled Exception")]
        public string ErrorUnhandledException {
            get {
                return ((string)(this["ErrorUnhandledException"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[General] Config.IO successfully ran")]
        public string LogConfigIo {
            get {
                return ((string)(this["LogConfigIo"]));
            }
            set {
                this["LogConfigIo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[General] Log config failed")]
        public string LogConfigFailed {
            get {
                return ((string)(this["LogConfigFailed"]));
            }
            set {
                this["LogConfigFailed"] = value;
            }
        }
    }
}
