//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit_console.Config.io {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Environments : global::System.Configuration.ApplicationSettingsBase {
        
        private static Environments defaultInstance = ((Environments)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Environments())));
        
        public static Environments Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hymans-cim-dev.company-net.com")]
        public string DevSharePoint {
            get {
                return ((string)(this["DevSharePoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hymans-cim.company-net.com")]
        public string IntSharePoint {
            get {
                return ((string)(this["IntSharePoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.clients.hymans.co.uk/")]
        public string LiveSharePoint {
            get {
                return ((string)(this["LiveSharePoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cns-crmhymans16.company-net.com/HymansDev/XRMServices/2011/Organization.sv" +
            "c")]
        public string DevCrm {
            get {
                return ((string)(this["DevCrm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cns-crmhymans16.company-net.com/CRMIntegration/XRMServices/2011/Organizati" +
            "on.svc")]
        public string IntCrm {
            get {
                return ((string)(this["IntCrm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crm.hymans.co.uk/hymansrobertson/XRMservices/2011/Organization.svc")]
        public string LiveCrm {
            get {
                return ((string)(this["LiveCrm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev")]
        public string Environment {
            get {
                return ((string)(this["Environment"]));
            }
        }
    }
}
